# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Le langage Golang
email: jabderrachid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ce blog présente le langage Go, du pourquoi au comment ainsi que les nombreuses possibilitées offertes par ce nouveau langage crée par Google
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jordanabderrachid.github.io" # the base hostname & protocol for your site
twitter_username: jesuisunelegend
github_username:  jordanabderrachid

# Build settings
markdown: kramdown
